//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndreyDplomWorkGameTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int id { get; set; }
        public Nullable<int> idUser { get; set; }
        public string TextMessage { get; set; }
    
        public virtual UserApp UserApp { get; set; }
    }
}
