//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndreyDplomWorkGameTest.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NiDboForDiplomAppWorkEntities : DbContext
    {
        public NiDboForDiplomAppWorkEntities()
            : base("name=NiDboForDiplomAppWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Chat> Chat { get; set; }
        public DbSet<IndiGameCatalog> IndiGameCatalog { get; set; }
        public DbSet<JanreGame> JanreGame { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TestGame> TestGame { get; set; }
        public DbSet<UserApp> UserApp { get; set; }
        public DbSet<UserGameBibliary> UserGameBibliary { get; set; }
    }
}
