//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndreyDplomWorkGameTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JanreGame
    {
        public JanreGame()
        {
            this.IndiGameCatalog = new HashSet<IndiGameCatalog>();
        }
    
        public int id { get; set; }
        public string JanreName { get; set; }
    
        public virtual ICollection<IndiGameCatalog> IndiGameCatalog { get; set; }
    }
}
