//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndreyDplomWorkGameTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApp
    {
        public UserApp()
        {
            this.Chat = new HashSet<Chat>();
            this.TestGame = new HashSet<TestGame>();
            this.UserGameBibliary = new HashSet<UserGameBibliary>();
        }
    
        public int id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string PhotoProfile { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Chat> Chat { get; set; }
        public virtual ICollection<TestGame> TestGame { get; set; }
        public virtual ICollection<UserGameBibliary> UserGameBibliary { get; set; }
    }
}
